# Generated by Django 3.0.8 on 2020-08-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200829_1204'),
        ('content', '0002_auto_20200826_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_projects', to='users.UserProfile'),
        ),
    ]
